name: "Blokir Nomor"
description: "Blokir nomor yang diinginkan"
title: "[Block] 08xx"
labels: "Request Blokir"
assignees: ""
issue_body: false
body:
- type: textarea
  id: nohp
  attributes:
    label: "Nomor"
    description: "Tulis nomor yang akan diblokir"
    placeholder: |
      
    value: |
      20
  validations:
    required: true
